'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { UserProfile } from '@/lib/api';
import styles from './UsernameSetupBanner.module.css';

interface Props {
  user: UserProfile;
}

export default function UsernameSetupBanner({ user }: Props) {
  const router = useRouter();
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    if (!user || !user.createdAt || !user.email) return;
    if (typeof window === 'undefined') return;

    const MIGRATION_DATE = new Date('2025-12-12T00:00:00Z');
    const DISMISS_KEY = 'patreek_legacy_username_dismissed';

    const userJoinedAt = new Date(user.createdAt);
    const isLegacyUser = userJoinedAt < MIGRATION_DATE;
    const emailPrefix = user.email.split('@')[0];
    const isAutoGenerated =
      user.username === emailPrefix || user.username === `${emailPrefix}_${user.id}`;
    const isDismissed = typeof window !== 'undefined' && localStorage.getItem(DISMISS_KEY);

    if (isLegacyUser && isAutoGenerated && !isDismissed) {
      setIsVisible(true);
    }
  }, [user]);

  const handleDismiss = () => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('patreek_legacy_username_dismissed', 'true');
    }
    setIsVisible(false);
  };

  const handleCustomize = () => {
    router.push('/settings/profile');
  };

  if (!isVisible || !user?.username) return null;

  return (
    <div className={styles.banner}>
      <div className={styles.copy}>
        <h3 className={styles.title}>New: Usernames have arrived!</h3>
        <p className={styles.subtitle}>
          We've reserved <strong>@{user.username}</strong> for you. Would you like to keep it or pick a new one?
        </p>
      </div>
      <div className={styles.actions}>
        <button type="button" className={styles.primary} onClick={handleCustomize}>
          Customize
        </button>
        <button type="button" className={styles.secondary} onClick={handleDismiss}>
          Keep it
        </button>
      </div>
    </div>
  );
}
